### PR TITLE
Handles child window via webViewCreateWebViewWithConfigurationForNavi…

### PR DESCRIPTION
**Pull request by alloyit**
Handles child window via webViewCreateWebViewWithConfigurationForNavigationActionWindowFeatures notifying the main NativeScript App with a custom "createWebViewWithConfiguration" event

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/Notalib/nativescript-webview-ext/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing.
  - [ ] On Android
  - [ ] On iOS 9
  - [ ] On iOS 10
  - [X] On iOS 11
  - [X] On iOS 12+
- [ ] Tests for the changes are included

## What is the current behavior?

Child window (i.e.: window.open) was not supported

## What is the new behavior?

New child window opening is intercepted and handled. An event is raised to notify the main App of the newly created WKWebView.

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by alloyit** [comment]
Hi Morten, I've updated the pull request following your hints.
Here follows a snippet to test our new code.

The HTML page:
`<WebViewExt (loadStarted)="onLoadStarted" (createWebViewWithConfiguration)="createWebViewWithConfiguration($event)" height="100%" #webView></WebViewExt>`


In Angular (Nativescript) we can open the new WKWebView in a new page:
`createWebViewWithConfiguration(args) {
    openWebViewNewPage(args && args.data);
}

openWebViewNewPage(webView) {
    if (!!webView) {
        setTimeout(() => {
            const page = new Page();
            const grid = new GridLayout();

            GridLayout.setColumn(webView, 0);
            GridLayout.setRow(webView, 1);
            grid.addChild(webView);

            var firstColumn = new ItemSpec(1, GridUnitType.STAR);
            var firstRow = new ItemSpec(1, GridUnitType.STAR);

            grid.addColumn(firstColumn);
            grid.addRow(firstRow);

            page.content = grid;

            const newActionBar = new ActionBar();
            let navButton = new NavigationButton();
            newActionBar.navigationButton = navButton;
            page.actionBar = newActionBar;
            page.actionBarHidden = false;

            topmost().navigate(() => page);

        }, 250)
    }
}
`

**Comment by m-abs** [comment]
Hi @alloyit,

Sorry we've been very busy over the summer.
Your PR looks very promising, but I can't say when we get around to it.

**Comment by alloyit** [comment]
Thanks for keeping in touch.

Regards,

Matteo Brusamolin

Alloy
Web: http://www.alloy.it/ <http://www.alloy.it/?utm_source=signature2&utm_medium=email&utm_campaign=Curiosity>

**Comment by m-abs** [comment]
Hey @alloyit 

I think we need a more platform independent way of handling `window.open` that also supports links with `target="_blank"`.

**Comment by m-abs** [comment]
I'm closing this PR, this is not how we'd want to solve this.

**Pull request closed without merging**
